version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
clone_folder: c:\CppProjectTemplate
init:
- cmd: >-

    echo %APPVEYOR_BUILD_WORKER_IMAGE%
install:
- cmd: >-
    
    git submodule update --init
before_build:
- cmd: >-
    
    mkdir build
    
    cd build
    
    cmake .. -G %generator%
build:
  project: c:\CppProjectTemplate\build\CppProjectTemplate.sln
  verbosity: minimal
  
after_build:
- cmd: c:\CppProjectTemplate\build\UnitTest\Release\unit_test.exe