version: 1.0.{build}
image: Visual Studio 2022
clone_folder: c:\hlsl2021
init:
- cmd: >-
    echo %APPVEYOR_BUILD_WORKER_IMAGE%
install:
- cmd: >-
    
    git submodule update --init
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake ..
build:
  project: c:\hlsl2021\build\hlsl2021.sln
  verbosity: minimal